# Generated by Django 4.0.3 on 2022-04-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titlu')),
                ('image', models.ImageField(upload_to='')),
                ('task', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'postare',
                'verbose_name_plural': 'postari',
            },
        ),
    ]
