# Generated by Django 4.0.3 on 2022-04-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_album_options_rename_task_album_desciere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='desc',
            field=models.TextField(default=1, verbose_name='text'),
            preserve_default=False,
        ),
    ]
