# Generated by Django 4.0.3 on 2022-04-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_album_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='desciere',
        ),
    ]
